(() => {
  const KF=window.KF={actions:{},KEY:'kidooflow_v07',LEGACY:'kidooflow_v06',DB_NAME:'kidooflow_media',DB_STORE:'images',selectedDate:null,selectedChild:'Hayden'};
  const DAY=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); KF.esc=esc;
  const cap=s=>s?s.charAt(0).toUpperCase()+s.slice(1):s; KF.cap=cap;
  const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; KF.dateKey=dateKey;
  const dateFromKey=k=>{const [y,m,d]=String(k).split('-').map(Number);return new Date(y,m-1,d,12)}; KF.dateFromKey=dateFromKey;
  const fmt=(k,opt='long')=>!k?'Sans date':new Intl.DateTimeFormat('fr-FR',opt==='short'?{day:'2-digit',month:'2-digit'}:{weekday:'long',day:'numeric',month:'long'}).format(dateFromKey(k)); KF.formatDate=fmt;
  KF.uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
  KF.normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  KF.toast=t=>{const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');clearTimeout(KF.toast.t);KF.toast.t=setTimeout(()=>e.classList.remove('show'),1900)};
  KF.state=()=>{try{return JSON.parse(localStorage.getItem(KF.KEY))||{}}catch{return{}}};
  KF.save=s=>{localStorage.setItem(KF.KEY,JSON.stringify(s));KF.render()};
  function ensure(){let s=KF.state();if(!s.initialized){let old={};try{old=JSON.parse(localStorage.getItem(KF.LEGACY))||{}}catch{}s={initialized:true,inbox:old.inbox||[],events:old.events||[],homework:old.homework||[],timetables:old.timetables||{Hayden:[],Théo:[]}}}s.inbox=s.inbox||[];s.events=s.events||[];s.homework=s.homework||[];s.timetables=s.timetables||{Hayden:[],Théo:[]};s.timetables.Hayden=s.timetables.Hayden||[];s.timetables['Théo']=s.timetables['Théo']||[];localStorage.setItem(KF.KEY,JSON.stringify(s))}
  KF.selectedDate=dateKey(new Date());
  KF.goto=page=>{document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===page));document.querySelectorAll('.bottom-nav [data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));window.scrollTo(0,0);KF.render()};
  KF.open=id=>{const e=document.getElementById(id);if(e){e.classList.add('show');e.setAttribute('aria-hidden','false')}};
  KF.close=id=>{const e=document.getElementById(id);if(e){e.classList.remove('show');e.setAttribute('aria-hidden','true')}};
  function occurs(ev,k){if(!ev.date)return false;if(ev.repeat!=='weekly')return ev.date===k;if(k<ev.date)return false;if((ev.exceptions||[]).includes(k))return false;return dateFromKey(k).getDay()===(ev.repeatWeekday??dateFromKey(ev.date).getDay())}
  KF.eventsFor=k=>(KF.state().events||[]).filter(e=>occurs(e,k)).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));
  function eventHtml(x){const source=x.sourceImageId?`<button class="source-mini" data-action="view-source" data-image-id="${x.sourceImageId}" data-source-text="${encodeURIComponent(x.sourceText||'')}">📎 Voir la capture source</button>`:'';const extra=[x.time&&x.endTime?`${x.time}–${x.endTime}`:x.time,x.materials?`🎒 ${x.materials}`:'',x.action?`✅ ${x.action}`:'',x.repeat==='weekly'?'↻ chaque semaine':''].filter(Boolean).join(' • ');return `<article class="event"><div class="ico">${x.icon||'📌'}</div><div><h4>${esc(x.title||'Événement')}</h4><p>${esc(x.text||'')}${extra?`<br><b>${esc(extra)}</b>`:''}</p></div><span class="tag">${esc(x.tag||'Info')}</span>${source}</article>`}
  function inboxHtml(x){const source=x.sourceImageId?`<div class="inbox-source"><button data-action="view-source" data-image-id="${x.sourceImageId}" data-source-text="${encodeURIComponent(x.sourceText||'')}">📎 Voir la capture</button></div>`:'';const when=x.date?`📅 ${cap(fmt(x.date))}${x.time?` • ${x.time}${x.endTime?`–${x.endTime}`:''}`:''}`:'📅 Date à confirmer';return `<article class="inbox-card"><div class="top"><span class="source">${x.icon||'🏫'} ${esc(x.source||'ÉcoleDirecte')}</span><span class="tag">${esc(x.tag||'École')}</span></div><h4>${esc(x.title||'Information')}</h4><p class="structured-line">${esc(when)}</p><p>${esc(x.text||'')}</p>${x.materials?`<p>🎒 ${esc(x.materials)}</p>`:''}${x.action?`<p class="action-line">✅ ${esc(x.action)}</p>`:''}${source}<div class="inbox-actions"><button data-action="ignore-inbox" data-id="${x.id}">Ignorer</button><button class="accept" data-action="accept-inbox" data-id="${x.id}">Ajouter ✓</button></div></article>`}
  function renderAgenda(){const anchor=dateFromKey(KF.selectedDate),monday=new Date(anchor);monday.setDate(anchor.getDate()-((anchor.getDay()+6)%7));const f=new Intl.DateTimeFormat('fr-FR',{weekday:'short'}),week=document.getElementById('agendaWeek');if(week)week.innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const k=dateKey(d);return `<button class="day ${k===KF.selectedDate?'active':''}" data-date="${k}"><span>${cap(f.format(d).replace('.',''))}</span><b>${d.getDate()}</b></button>`}).join('');const lab=document.getElementById('selectedDateLabel');if(lab)lab.textContent=cap(fmt(KF.selectedDate));const list=document.getElementById('agendaList'),ev=KF.eventsFor(KF.selectedDate);if(list)list.innerHTML=ev.length?ev.map(eventHtml).join(''):'<div class="empty">Aucun événement ce jour-là.</div>'}
  function renderTimetable(){const s=KF.state(),tt=(s.timetables?.[KF.selectedChild]||[]).slice().sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start));const title=document.getElementById('timetableTitle');if(title)title.textContent=`${KF.selectedChild} • semaine type`;const by={1:[],2:[],3:[],4:[],5:[]};tt.forEach(c=>{if(by[c.day])by[c.day].push(c)});const el=document.getElementById('timetableView');if(el)el.innerHTML=[1,2,3,4,5].map(day=>`<div class="tt-day"><div class="tt-day-title">${DAY[day]}</div>${by[day].length?by[day].map(c=>`<div class="course"><time>${esc(c.start)}–${esc(c.end)}</time><b>${esc(c.subject)}</b><button class="tiny-delete" data-action="delete-course" data-id="${c.id}" data-child="${esc(KF.selectedChild)}">✕</button></div>`).join(''):'<div class="empty" style="padding:8px">—</div>'}</div>`).join('')}
  function renderHomework(){const s=KF.state(),hw=(s.homework||[]).filter(h=>h.child===KF.selectedChild).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));const title=document.getElementById('homeworkTitle');if(title)title.textContent=`${KF.selectedChild} • à venir`;const el=document.getElementById('homeworkView');if(el)el.innerHTML=hw.length?hw.map(h=>`<div class="homework-item ${h.done?'done':''}"><div><span class="homework-date">${h.dueDate?cap(fmt(h.dueDate)):'Date à confirmer'}</span><br><b>${esc(h.subject||'Devoir')}</b><p>${esc(h.task)}</p></div><div class="homework-actions"><button class="done-btn" data-action="toggle-homework" data-id="${h.id}">${h.done?'↩':'✓'}</button><button class="delete-btn" data-action="delete-homework" data-id="${h.id}">✕</button></div></div>`).join(''):'<div class="empty">Aucun devoir enregistré.</div>'}
  KF.render=()=>{const s=KF.state(),today=dateKey(new Date()),ev=KF.eventsFor(today),hw=(s.homework||[]).filter(h=>!h.done&&(!h.dueDate||h.dueDate>=today)),courses=(s.timetables?.Hayden||[]).filter(c=>c.day===new Date().getDay());const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};set('inboxCount',s.inbox.length);set('inboxChip',`${s.inbox.length} élément${s.inbox.length===1?'':'s'} Inbox`);set('eventCount',ev.length);set('homeworkCount',hw.length);set('timetableCount',courses.length);const priorities=[...ev];if(hw.length)priorities.push({icon:'📚',title:`${hw.length} devoir${hw.length>1?'s':''} à venir`,text:hw.slice(0,2).map(h=>`${h.child}: ${h.subject}`).join(' • '),tag:'Devoirs'});if(courses.length)priorities.push({icon:'🗓️',title:`${courses.length} cours Hayden aujourd’hui`,text:courses.slice(0,3).map(c=>`${c.start} ${c.subject}`).join(' • '),tag:'Collège'});const tl=document.getElementById('todayList');if(tl)tl.innerHTML=priorities.length?priorities.map(eventHtml).join(''):'<div class="empty">Rien de prioritaire aujourd’hui 🎉</div>';const il=document.getElementById('inboxList');if(il)il.innerHTML=s.inbox.length?s.inbox.map(inboxHtml).join(''):'<div class="empty">Inbox vide 🎉</div>';renderAgenda();renderTimetable();renderHomework();document.querySelectorAll('#childSwitch [data-child]').forEach(b=>b.classList.toggle('active',b.dataset.child===KF.selectedChild))};
  KF.acceptInbox=id=>{const s=KF.state(),x=s.inbox.find(i=>i.id===id);if(!x)return;if(!x.date){KF.toast('Confirme d’abord une date');return}s.inbox=s.inbox.filter(i=>i.id!==id);s.events.push({...x,id:KF.uid('ev')});KF.selectedDate=x.date;KF.save(s);KF.toast('Ajouté à l’agenda ✓')};
  KF.ignoreInbox=id=>{const s=KF.state();s.inbox=s.inbox.filter(i=>i.id!==id);KF.save(s)};
  document.addEventListener('click',e=>{const d=e.target.closest('.day[data-date]');if(d){KF.selectedDate=d.dataset.date;renderAgenda();return}const ch=e.target.closest('[data-child]');if(ch){KF.selectedChild=ch.dataset.child;KF.render();return}const b=e.target.closest('button');if(!b)return;if(b.dataset.nav){KF.goto(b.dataset.nav);return}const a=b.dataset.action,id=b.dataset.id;if(KF.actions[a]){KF.actions[a](b,e);return}if(a==='accept-inbox')return KF.acceptInbox(id);if(a==='ignore-inbox')return KF.ignoreInbox(id);if(a==='today'){KF.selectedDate=dateKey(new Date());return renderAgenda()}if(a==='prev-week'||a==='next-week'){const dt=dateFromKey(KF.selectedDate);dt.setDate(dt.getDate()+(a==='next-week'?7:-7));KF.selectedDate=dateKey(dt);return renderAgenda()}if(a==='toggle-homework'){const s=KF.state(),h=s.homework.find(x=>x.id===id);if(h)h.done=!h.done;return KF.save(s)}if(a==='delete-homework'){const s=KF.state();s.homework=s.homework.filter(x=>x.id!==id);return KF.save(s)}if(a==='delete-course'){const s=KF.state(),c=b.dataset.child;s.timetables[c]=(s.timetables[c]||[]).filter(x=>x.id!==id);return KF.save(s)}if(a==='add-child')return KF.toast('Ajout d’enfant prévu avec les comptes');if(a==='appointment'){document.getElementById('inputText').value='Dentiste Théo mardi 6 octobre à 16h30.';return KF.goto('add')}if(a==='sport'){document.getElementById('inputText').value='Hayden entraînement football mercredi à 17h30 toutes les semaines.';return KF.goto('add')}if(a==='voice'){KF.goto('add');return document.getElementById('inputText').focus()}if(a==='install')return KF.toast('iPhone : Partager → Sur l’écran d’accueil')});
  ensure();KF.render();
})();