(() => {
  const KF=window.KF;if(!KF)return;
  const MONTHS={janvier:0,fevrier:1,'février':1,mars:2,avril:3,mai:4,juin:5,juillet:6,aout:7,'août':7,septembre:8,octobre:9,novembre:10,decembre:11,'décembre':11};
  const DAY_ABBR={lun:1,lundi:1,mar:2,mardi:2,mer:3,mercredi:3,jeu:4,jeudi:4,ven:5,vendredi:5,sam:6,samedi:6,dim:0,dimanche:0};
  const DAY_NAMES=['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
  const SUBJECT_HINTS=['mathématiques','maths','français','anglais','histoire','géographie','svt','sciences','physique','chimie','technologie','eps','sport','musique','arts','espagnol','allemand','latin','emc','est','education','éducation','accompagnement'];
  let importMode='message',selectedPhotos=[],pending=null;
  const n=KF.normalize,esc=KF.esc,cap=KF.cap;

  function parseDateText(raw,baseYear=new Date().getFullYear()){
    const t=n(raw),months=Object.keys(MONTHS).sort((a,b)=>b.length-a.length).join('|');
    let m=t.match(new RegExp(`(?:(lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche)\\s+)?(\\d{1,2})\\s+(${months})(?:\\s+(\\d{4}))?`,'i'));
    if(m){let y=m[4]?+m[4]:baseYear,d=new Date(y,MONTHS[m[3]],+m[2],12);if(!m[4]&&d<new Date(Date.now()-45*864e5))d=new Date(y+1,MONTHS[m[3]],+m[2],12);return KF.dateKey(d)}
    m=t.match(/\b(\d{1,2})[\/\.\-](\d{1,2})(?:[\/\.\-](\d{2,4}))?\b/);if(m){let y=m[3]?+m[3]:baseYear;if(y<100)y+=2000;return KF.dateKey(new Date(y,+m[2]-1,+m[1],12))}return '';
  }
  function dateCandidates(text){
    const clean=String(text||'').replace(/[ \t]+/g,' '),low=n(clean),greet=low.match(/\b(bonjour|bonsoir)\b/),body=greet?greet.index:Math.floor(low.length*.25),out=[],months=Object.keys(MONTHS).sort((a,b)=>b.length-a.length).join('|'),rx=new RegExp(`(?:(lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche)\\s+)?(\\d{1,2})\\s+(${months})(?:\\s+(\\d{4}))?`,'gi');
    for(const m of clean.matchAll(rx)){const key=parseDateText(m[0]);if(!key)continue;const idx=m.index||0,ctx=n(clean.slice(Math.max(0,idx-90),Math.min(clean.length,idx+120)));let score=2;const exception=/n['’ ]?aura pas lieu|pas lieu|annul|exception|par contre/.test(ctx);if(/a partir de|à partir de|des ce|dès ce|a compter du|à compter du/.test(ctx))score+=12;if(/auront lieu|aura lieu|seance|séance|sortie|rendez|pour le/.test(ctx))score+=6;if(idx<body)score-=8;if(exception)score-=12;out.push({key,raw:m[0],index:idx,score,exception})}
    return out.sort((a,b)=>b.score-a.score||a.index-b.index);
  }
  function messageTitle(text){
    const lines=String(text||'').split(/\r?\n/).map(s=>s.trim()).filter(Boolean),ignore=/boite de reception|boîte de réception|a moi|à moi|mme |m\. |monsieur|madame|lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche|bonjour|bonsoir|cordialement|ecoledirecte|emploi du temps/i;
    const first=lines.slice(0,10).find(l=>l.length>=3&&l.length<=60&&!ignore.test(l)&&!/^\d/.test(l));if(first)return first.replace(/^objet\s*:\s*/i,'').trim();
    const low=n(text);for(const [rx,title] of [[/rugby/,'Rugby'],[/piscine/,'Piscine'],[/cross/,'Cross'],[/voyage/,'Voyage scolaire'],[/sortie/,'Sortie scolaire'],[/reunion|réunion/,'Réunion'],[/rendez[- ]?vous/,'Rendez-vous']])if(rx.test(low))return title;return 'Information ÉcoleDirecte';
  }
  function parseMessage(text){
    const clean=String(text||'').trim(),low=n(clean),dates=dateCandidates(clean),primary=dates.find(d=>!d.exception),exceptions=[...new Set(dates.filter(d=>d.exception).map(d=>d.key))];let start='',end='';
    let tm=low.match(/(?:de|entre)\s*(\d{1,2})\s*h\s*([0-5]\d)?\s*(?:a|à|et|-)\s*(\d{1,2})\s*h\s*([0-5]\d)?/);if(tm){start=`${String(+tm[1]).padStart(2,'0')}:${tm[2]||'00'}`;end=`${String(+tm[3]).padStart(2,'0')}:${tm[4]||'00'}`}
    if(!tm){tm=low.match(/(\d{1,2})[:h]([0-5]\d)\s*(?:a|à|-)\s*(\d{1,2})[:h]([0-5]\d)/);if(tm){start=`${String(+tm[1]).padStart(2,'0')}:${tm[2]}`;end=`${String(+tm[3]).padStart(2,'0')}:${tm[4]}`}}
    let repeat='',repeatWeekday=null;const wr=low.match(/(?:tous? les?|chaque|auront lieu le|aura lieu le|le)\s+(lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche)(?:\s+matin|\s+apres-midi)?/);if(wr&&(low.includes('chaque')||low.includes('tous')||low.includes('auront lieu le')||low.includes('aura lieu le')||low.includes("jusqu'aux vacances")||low.includes('jusqu aux vacances'))){repeat='weekly';repeatWeekday=DAY_ABBR[wr[1]]}
    let materials='';const sent=clean.split(/(?<=[.!?])\s+/).find(s=>/prévoir|prevoir|avoir sur eux|apporter|venir avec|amener/i.test(s));if(sent){materials=sent.replace(/^.*?(?:avoir sur eux|prévoir|prevoir|apporter|venir avec|amener)\s*/i,'').replace(/^(une?|des?|le|la|les)\s+/i,'').replace(/\.$/,'').trim().replace(/\bet prévoir\b/gi,',').replace(/\bdes\b/gi,'').replace(/\bune\b/gi,'').replace(/\s+,/g,',').replace(/,\s*,/g,',').replace(/\s{2,}/g,' ').trim()}
    let action='';if(/besoin d['’ ]?un parent.*accompagn|parent pour nous accompagner/.test(low))action='Répondre si disponible pour accompagner';else if(/merci de (?:me )?(?:le )?faire savoir|merci de repondre|merci de répondre/.test(low))action='Répondre au message';else if(/autorisation|signer/.test(low))action='Signer / remettre l’autorisation';
    let category='Message',icon='💬';if(/rugby|piscine|cross|sport|eps|stade|gymnase/.test(low)){category='Sport scolaire';icon='🏉'}else if(/sortie|voyage|visite|spectacle|excursion/.test(low)){category='Événement';icon='🚌'}else if(/absence|retard|sanction|vie scolaire/.test(low)){category='Vie scolaire';icon='🏫'}else if(action)category='Action';
    return {title:messageTitle(clean),category,icon,date:primary?.key||'',start,end,repeat,repeatWeekday,exceptions,materials,action,clean};
  }
  function canonicalSubject(raw){const x=n(raw).replace(/[^a-z0-9]+/g,' ').trim();if(!x)return '';if(/ed physique|physique.*sport|eps|sport/.test(x))return 'EPS';if(/mathem/.test(x))return 'Mathématiques';if(/francais/.test(x))return 'Français';if(/anglais/.test(x))return /lv1/.test(x)?'Anglais LV1':'Anglais';if(/histoire.*geo|geo.*histoire/.test(x))return 'Histoire-Géographie';if(/histoire/.test(x))return 'Histoire';if(/geograph/.test(x))return 'Géographie';if(/technolog/.test(x))return 'Technologie';if(/^arts?$|arts plast/.test(x))return 'Arts';if(/physique.*chimie/.test(x))return 'Physique-Chimie';if(/^svt$|sciences vie/.test(x))return 'SVT';if(/acomp|accomp/.test(x))return 'Accompagnement';if(/^est$/.test(x))return 'EST';if(/education/.test(x))return 'Éducation';if(/musique/.test(x))return 'Musique';return raw.replace(/\s+/g,' ').trim()}
  function meaningful(line){return line.length>3&&!/ecoledirecte|boite de reception|emploi du temps|menu|deconnexion|actualites|messagerie|notes|vie scolaire/i.test(n(line))}
  function parseHomework(text){const lines=String(text||'').split(/\r?\n/).map(x=>x.replace(/\s+/g,' ').trim()).filter(Boolean);let currentDate='',currentSubject='',rows=[];for(const line of lines){const d=parseDateText(line);if(d&&/pour|lundi|mardi|mercredi|jeudi|vendredi|samedi|dimanche|a faire|à faire/i.test(line)){currentDate=d;continue}const subj=SUBJECT_HINTS.find(s=>n(line).includes(n(s)));if(subj&&line.length<55){currentSubject=canonicalSubject(line);continue}if(!meaningful(line))continue;if(/exercice|\bex\b|lire|lecture|apprendre|réviser|reviser|finir|faire|préparer|preparer|page|dictée|dictee|leçon|lecon|rendre|copier/i.test(line))rows.push({id:KF.uid('hwrow'),subject:currentSubject||'À préciser',task:line,dueDate:d||currentDate||''})}if(!rows.length){const body=lines.filter(meaningful).filter(l=>!parseDateText(l)).slice(-3).join(' ');rows=[{id:KF.uid('hwrow'),subject:currentSubject||'À préciser',task:body||'Devoir à préciser',dueDate:currentDate||''}]}return rows.slice(0,12)}

  function patchDom(){const input=document.getElementById('photoInput');if(input)input.multiple=true;const ws=document.getElementById('photoWorkspace');if(ws&&!document.getElementById('photoGallery')){const g=document.createElement('div');g.id='photoGallery';g.className='photo-gallery';const preview=document.getElementById('photoPreview');ws.insertBefore(g,preview)}const school=document.querySelector('.school-card-head');if(school&&!school.querySelector('[data-action="clear-timetable"]')){const imp=school.querySelector('[data-action="import-timetable"]');if(imp){const clear=document.createElement('button');clear.className='compact-btn';clear.dataset.action='clear-timetable';clear.textContent='Effacer';imp.parentElement.insertBefore(clear,imp)}}}
  function resetImport(){selectedPhotos=[];document.getElementById('photoInput').value='';document.getElementById('photoEmpty').classList.remove('hidden');document.getElementById('photoWorkspace').classList.add('hidden');['messageResult','homeworkResult','timetableResult','ocrProgress'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));const g=document.getElementById('photoGallery');if(g)g.innerHTML=''}
  function configure(mode){importMode=mode;resetImport();const cfg={message:['🏫','Message ÉcoleDirecte','Choisis une capture de message.','KidooFlow séparera la date d’envoi de la vraie date utile.'],homework:['📚','Importer des devoirs','Choisis une capture ÉcoleDirecte ou du cahier.','Les devoirs seront convertis en lignes modifiables.'],timetable:['🗓️','Importer l’emploi du temps','Choisis 1 à 4 captures de la même semaine.','Ajoute le matin puis l’après-midi : les captures seront fusionnées.']}[mode];document.getElementById('importEmoji').textContent=cfg[0];document.getElementById('importTitle').textContent=cfg[1];document.getElementById('importEmptyTitle').textContent=cfg[2];document.getElementById('importSubtitle').textContent=cfg[3];document.getElementById('importEmptyHint').textContent=cfg[3];KF.open('importModal')}
  function compress(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=2000,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve({data:c.toDataURL('image/jpeg',.86),name:file.name||'capture.jpg'})};img.onerror=()=>{URL.revokeObjectURL(url);reject()};img.src=url})}
  async function select(files){const list=[...files];if(!list.length)return;try{const add=[];for(const f of list.slice(0,4))add.push(await compress(f));selectedPhotos=importMode==='timetable'?[...selectedPhotos,...add].slice(0,4):[add[0]];document.getElementById('photoEmpty').classList.add('hidden');document.getElementById('photoWorkspace').classList.remove('hidden');document.getElementById('photoGallery').innerHTML=selectedPhotos.map((p,i)=>`<div class="photo-thumb"><img src="${p.data}" alt="Capture ${i+1}"><span>${esc(p.name)}</span></div>`).join('');document.getElementById('photoName').textContent=`${selectedPhotos.length} capture${selectedPhotos.length>1?'s':''} sélectionnée${selectedPhotos.length>1?'s':''}`;KF.toast('Capture prête ✓')}catch{KF.toast('Impossible de lire cette image')}}
  const progress=(v,t)=>{document.getElementById('ocrProgressBar').style.width=`${Math.round(v*100)}%`;document.getElementById('ocrProgressText').textContent=t};
  async function runOcr(){if(!selectedPhotos.length)return KF.toast('Choisis une image');if(!window.Tesseract)return KF.toast('OCR indisponible');const btn=document.getElementById('ocrButton');btn.disabled=true;document.getElementById('ocrProgress').classList.remove('hidden');const results=[];try{for(let i=0;i<selectedPhotos.length;i++){progress(i/selectedPhotos.length,`Lecture ${i+1}/${selectedPhotos.length}…`);const r=await Tesseract.recognize(selectedPhotos[i].data,'fra',{logger:m=>{if(m.progress!=null)progress((i+m.progress)/selectedPhotos.length,`Lecture ${i+1}/${selectedPhotos.length}…`)}});results.push(r)}progress(1,'Analyse terminée');if(importMode==='message')fillMessage(results.map(r=>r.data.text||'').join('\n'));else if(importMode==='homework')fillHomework(results.map(r=>r.data.text||'').join('\n'));else await fillTimetable(results);KF.toast('Analyse terminée ✓')}catch(e){console.error(e);KF.toast('OCR incomplet : corrige les champs manuellement')}finally{btn.disabled=false}}
  function fillMessage(text){const m=parseMessage(text),cat=document.getElementById('msgCategory');document.getElementById('ocrText').value=text;document.getElementById('msgTitle').value=m.title;if([...cat.options].some(o=>o.value===m.category))cat.value=m.category;document.getElementById('msgDate').value=m.date;document.getElementById('msgStart').value=m.start;document.getElementById('msgEnd').value=m.end;document.getElementById('msgRepeat').value=m.repeat;document.getElementById('msgMaterials').value=m.materials;document.getElementById('msgAction').value=m.action;document.getElementById('msgExceptions').value=m.exceptions.join(', ');document.getElementById('messageDetected').innerHTML=[`🎯 Objet : <strong>${esc(m.title)}</strong>`,m.date?`📅 Date utile : ${esc(cap(KF.formatDate(m.date)))}`:'📅 Date à confirmer',m.start?`🕒 ${esc(m.start)}${m.end?`–${esc(m.end)}`:''}`:'',m.repeat==='weekly'?'↻ Récurrence hebdomadaire':'',m.exceptions.length?`⛔ Exception : ${m.exceptions.map(x=>esc(cap(KF.formatDate(x)))).join(', ')}`:''].filter(Boolean).join('<br>');document.getElementById('messageResult').classList.remove('hidden')}
  const homeworkRow=r=>`<div class="edit-row" data-row-id="${r.id}"><button class="remove-row" data-action="remove-edit-row">✕</button><div class="edit-row-grid"><input data-field="subject" value="${esc(r.subject||'')}" placeholder="Matière"><input data-field="dueDate" type="date" value="${esc(r.dueDate||'')}"></div><input data-field="task" value="${esc(r.task||'')}" placeholder="Travail à faire" style="width:100%;margin-top:7px"></div>`;
  function fillHomework(text){document.getElementById('homeworkOcrText').value=text;document.getElementById('homeworkRows').innerHTML=parseHomework(text).map(homeworkRow).join('');document.getElementById('homeworkResult').classList.remove('hidden')}
  const courseRow=c=>`<div class="edit-row" data-course-id="${c.id||KF.uid('course')}"><button class="remove-row" data-action="remove-edit-row">✕</button><div class="edit-row-grid"><select data-field="day">${[1,2,3,4,5].map(d=>`<option value="${d}" ${+c.day===d?'selected':''}>${DAY_NAMES[d]}</option>`).join('')}</select><input data-field="subject" value="${esc(c.subject||'')}" placeholder="Matière"></div><div class="edit-row-grid" style="margin-top:7px"><input data-field="start" type="time" value="${esc(c.start||'08:00')}"><input data-field="end" type="time" value="${esc(c.end||'09:00')}"></div></div>`;

  function imagePixels(photo){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0);resolve({width:c.width,height:c.height,data:ctx.getImageData(0,0,c.width,c.height).data})};img.onerror=reject;img.src=photo.data})}
  function getWords(result){if(result.data.words?.length)return result.data.words;const out=[];(result.data.blocks||[]).forEach(b=>(b.paragraphs||[]).forEach(p=>(p.lines||[]).forEach(l=>(l.words||[]).forEach(w=>out.push(w)))));return out}
  const bbox=w=>{const b=w.bbox||{};return{x0:b.x0||0,y0:b.y0||0,x1:b.x1||0,y1:b.y1||0}};
  function detectCourses(result,pix){
    const words=getWords(result).filter(w=>w.text?.trim()).map(w=>({...w,n:n(w.text),b:bbox(w)})),W=pix.width,H=pix.height,dayMap={};
    words.forEach(w=>{const tok=w.n.replace(/[^a-z]/g,''),key=Object.keys(DAY_ABBR).find(k=>tok.startsWith(k));if(key){const d=DAY_ABBR[key];if(d>=1&&d<=5&&!dayMap[d])dayMap[d]={x:(w.b.x0+w.b.x1)/2,y:w.b.y1}}});let centers=[1,2,3,4,5].map(d=>dayMap[d]?.x).filter(Boolean);
    if(centers.length<3){const left=W*.06,width=W*.93/7;for(let d=1;d<=5;d++)dayMap[d]={x:left+(d-.5)*width,y:H*.13};centers=[1,2,3,4,5].map(d=>dayMap[d].x)}
    const ds=centers.slice(1).map((x,i)=>x-centers[i]).filter(x=>x>20).sort((a,b)=>a-b),colW=ds.length?ds[Math.floor(ds.length/2)]:W*.93/7,headerY=Math.max(...Object.values(dayMap).map(x=>x.y||0),H*.08)+20,hours={};
    words.forEach(w=>{const digits=w.text.replace(/\D/g,''),h=+digits,xc=(w.b.x0+w.b.x1)/2;if(digits.length<=2&&h>=7&&h<=20&&xc<Math.min(...centers)-colW*.42){const yc=(w.b.y0+w.b.y1)/2;if(!hours[h])hours[h]=yc}});const hs=Object.entries(hours).map(([h,y])=>({h:+h,y})).sort((a,b)=>a.h-b.h),near=y=>hs.length?hs.reduce((a,b)=>Math.abs(b.y-y)<Math.abs(a.y-y)?b:a,hs[0]).h:null,idx=(x,y)=>(y*W+x)*4,isColor=(x,y)=>{const i=idx(x,y),r=pix.data[i],g=pix.data[i+1],b=pix.data[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),avg=(r+g+b)/3;return (mx-mn>26||avg<208)&&avg>40},courses=[];
    for(let day=1;day<=5;day++){const cx=dayMap[day].x,x0=Math.max(0,Math.round(cx-colW*.38)),x1=Math.min(W-1,Math.round(cx+colW*.38)),scores=[];for(let y=Math.round(headerY);y<H;y+=2){let hit=0,total=0;for(let x=x0;x<=x1;x+=8){total++;if(isColor(x,y))hit++}scores.push({y,score:hit/Math.max(1,total)})}const runs=[];let st=null,last=null;for(const s of scores){if(s.score>.28){if(st==null)st=s.y;last=s.y}else if(st!=null&&s.y-last<=8){}else if(st!=null){if(last-st>22)runs.push([st,last]);st=last=null}}if(st!=null&&last-st>22)runs.push([st,last]);for(const [y0,y1] of runs){const inside=words.filter(w=>{const x=(w.b.x0+w.b.x1)/2,y=(w.b.y0+w.b.y1)/2;return x>x0&&x<x1&&y>y0-8&&y<y1+8&&!/^(lun|mar|mer|jeu|ven|sam|dim)/.test(w.n)&&!/^\d{1,2}$/.test(w.text.trim())}).sort((a,b)=>Math.abs(a.b.y0-b.b.y0)>14?a.b.y0-b.b.y0:a.b.x0-b.b.x0);let subject=canonicalSubject(inside.map(w=>w.text).join(' '));if(!subject||subject.length<2)continue;const h0=near(y0+(y1-y0)*.25),h1=near(y1-(y1-y0)*.25);if(h0==null||h1==null)continue;courses.push({id:KF.uid('course'),day,start:`${String(h0).padStart(2,'0')}:00`,end:`${String(h1+1).padStart(2,'0')}:00`,subject})}}
    return courses;
  }
  function dedupe(courses){const out=[];for(const c of courses){if(!out.some(x=>x.day===c.day&&x.start===c.start&&x.end===c.end&&n(x.subject)===n(c.subject)))out.push(c)}return out.sort((a,b)=>a.day-b.day||a.start.localeCompare(b.start))}
  async function fillTimetable(results){const all=[];for(let i=0;i<results.length;i++)all.push(...detectCourses(results[i],await imagePixels(selectedPhotos[i])));const merged=dedupe(all);document.getElementById('courseRows').innerHTML=(merged.length?merged:[{id:KF.uid('course'),day:1,start:'08:00',end:'09:00',subject:''}]).map(courseRow).join('');document.getElementById('timetableOcrText').value=results.map((r,i)=>`--- Capture ${i+1} ---\n${r.data.text||''}`).join('\n\n');document.getElementById('timetableSummary').innerHTML=merged.length?`✅ <strong>${merged.length} cours</strong> détectés sur ${selectedPhotos.length} capture${selectedPhotos.length>1?'s':''}. Vérifie surtout les matières tronquées.`:'⚠️ La grille n’a pas été suffisamment comprise. Ajoute/corrige les cours ci-dessous.';document.getElementById('timetableResult').classList.remove('hidden')}
  function readRows(container,type){return [...container.querySelectorAll('.edit-row')].map(row=>{const get=f=>row.querySelector(`[data-field="${f}"]`)?.value?.trim()||'';return type==='hw'?{subject:get('subject'),dueDate:get('dueDate'),task:get('task')}:{day:+get('day'),subject:get('subject'),start:get('start'),end:get('end')}}).filter(x=>type==='hw'?x.task:x.subject)}
  function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(KF.DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(KF.DB_STORE))r.result.createObjectStore(KF.DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function putImage(id,data){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(KF.DB_STORE,'readwrite');tx.objectStore(KF.DB_STORE).put(data,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
  async function getImage(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(KF.DB_STORE,'readonly'),r=tx.objectStore(KF.DB_STORE).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function sendMessage(){const raw=document.getElementById('ocrText').value.trim(),date=document.getElementById('msgDate').value;if(!date)return KF.toast('Confirme une date');let imageId='';if(selectedPhotos[0]){imageId=KF.uid('img');try{await putImage(imageId,selectedPhotos[0].data)}catch{imageId=''}}const parsed=parseMessage(raw),repeat=document.getElementById('msgRepeat').value,item={id:KF.uid('in'),source:'ÉcoleDirecte • capture',icon:parsed.icon,title:document.getElementById('msgTitle').value.trim()||'Information ÉcoleDirecte',text:`${document.getElementById('msgChild').value} • ${raw.slice(0,240)}`,tag:document.getElementById('msgCategory').value,date,time:document.getElementById('msgStart').value,endTime:document.getElementById('msgEnd').value,repeat,repeatWeekday:repeat==='weekly'?(parsed.repeatWeekday??KF.dateFromKey(date).getDay()):null,exceptions:document.getElementById('msgExceptions').value.split(',').map(x=>x.trim()).filter(Boolean),materials:document.getElementById('msgMaterials').value.trim(),action:document.getElementById('msgAction').value.trim(),sourceImageId:imageId,sourceText:raw};const s=KF.state();s.inbox=[item,...s.inbox];KF.save(s);KF.close('importModal');resetImport();KF.goto('inbox');KF.toast('Message structuré dans l’Inbox ✓')}
  function saveHomework(){const rows=readRows(document.getElementById('homeworkRows'),'hw');if(!rows.length)return KF.toast('Aucun devoir à enregistrer');const child=document.getElementById('hwChild').value,source=document.getElementById('hwSource').value,s=KF.state();s.homework.push(...rows.map(r=>({...r,id:KF.uid('hw'),child,source,done:false})));KF.selectedChild=child;KF.save(s);KF.close('importModal');resetImport();KF.goto('children');KF.toast(`${rows.length} devoir${rows.length>1?'s':''} enregistré${rows.length>1?'s':''} ✓`)}
  function saveTimetable(){const rows=dedupe(readRows(document.getElementById('courseRows'),'tt').map(r=>({...r,id:KF.uid('course')})));if(!rows.length)return KF.toast('Aucun cours à enregistrer');const child=document.getElementById('ttChild').value,mode=document.getElementById('ttReplace').value,s=KF.state();s.timetables[child]=mode==='replace'?rows:dedupe([...(s.timetables[child]||[]),...rows]);KF.selectedChild=child;KF.save(s);KF.close('importModal');resetImport();KF.goto('children');KF.toast(`Emploi du temps ${child} enregistré ✓`)}
  async function viewSource(b){try{const data=await getImage(b.dataset.imageId);if(!data)return KF.toast('Capture introuvable sur cet appareil');document.getElementById('sourceImage').src=data;document.getElementById('sourceText').textContent=decodeURIComponent(b.dataset.sourceText||'');KF.open('sourceModal')}catch{KF.toast('Impossible d’ouvrir la capture')}}

  KF.actions['import-message']=()=>configure('message');KF.actions['import-homework']=()=>configure('homework');KF.actions['import-timetable']=()=>configure('timetable');KF.actions['choose-photo']=()=>document.getElementById('photoInput').click();KF.actions['close-import']=()=>KF.close('importModal');KF.actions['run-ocr']=()=>runOcr();KF.actions['reanalyze-message']=()=>fillMessage(document.getElementById('ocrText').value);KF.actions['send-message-inbox']=()=>sendMessage();KF.actions['save-homework']=()=>saveHomework();KF.actions['save-timetable']=()=>saveTimetable();KF.actions['add-homework-row']=()=>document.getElementById('homeworkRows').insertAdjacentHTML('beforeend',homeworkRow({id:KF.uid('hwrow'),subject:'',task:'',dueDate:''}));KF.actions['add-course-row']=()=>document.getElementById('courseRows').insertAdjacentHTML('beforeend',courseRow({id:KF.uid('course'),day:1,start:'08:00',end:'09:00',subject:''}));KF.actions['remove-edit-row']=b=>b.closest('.edit-row')?.remove();KF.actions['view-source']=b=>viewSource(b);KF.actions['close-source']=()=>KF.close('sourceModal');KF.actions['clear-timetable']=()=>{const s=KF.state();s.timetables[KF.selectedChild]=[];KF.save(s);KF.toast(`Emploi du temps ${KF.selectedChild} effacé`)};
  KF.actions['analyze']=()=>{const text=document.getElementById('inputText').value.trim();if(!text)return KF.toast('Ajoute une information');const m=parseMessage(text);pending={id:KF.uid('ev'),icon:m.icon,title:m.title,text:text.slice(0,220),tag:m.category,date:m.date||KF.dateKey(new Date()),time:m.start,endTime:m.end,action:m.action,materials:m.materials,repeat:m.repeat,repeatWeekday:m.repeatWeekday,exceptions:m.exceptions};document.getElementById('analysisBody').innerHTML=`<ul><li>Objet : <b>${esc(pending.title)}</b></li><li>Date : <b>${esc(cap(KF.formatDate(pending.date)))}</b></li><li>Horaire : <b>${esc(pending.time||'à confirmer')}</b></li><li>Catégorie : <b>${esc(pending.tag)}</b></li></ul>`;document.getElementById('analysis').classList.remove('hidden')};
  KF.actions['save-analysis']=()=>{if(!pending)return;const s=KF.state();s.events.push(pending);KF.selectedDate=pending.date;KF.save(s);pending=null;document.getElementById('inputText').value='';document.getElementById('analysis').classList.add('hidden');KF.goto('agenda')};
  const input=document.getElementById('photoInput');if(input)input.addEventListener('change',e=>select(e.target.files));patchDom();
})();